"""Prop descriptor map for Split Node.

When a chapter title or a shot's narration/scene mentions a prop keyword, the
matching VISUAL DESCRIPTOR is injected into the image prompt so the prop
appears in the frame with the correct context (e.g. 'vault' -> a massive steel
bank vault door; 'academic halls' -> a grand university library). Joe 2026-08-09.

Each entry: lowercase keyword (or tuple of aliases) -> visual descriptor phrase.
"""

PROP_VISUALS = {
    # ---- Vaults / security / banking ----
    "vault": "a massive steel bank vault door with a huge spin dial, reinforced concrete walls, cold fluorescent light",
    "bank vault": "a fortress-like bank vault interior with rows of safety deposit boxes",
    "safety deposit box": "a wall of small numbered steel safety deposit boxes in a bank vault",
    "security": "a dark security control room with rows of monitors and blinking lights",
    "safe": "a heavy steel safe with a combination dial, slightly ajar",
    "tunnel": "a long dimly-lit concrete tunnel receding into darkness",
    "lock": "an old brass padlock on a heavy steel door",
    "key": "a single antique brass key held in sharp focus",
    "keycard": "a sleek corporate keycard with a magnetic strip",
    "alarm": "a red wall-mounted security alarm panel with a glowing warning light",
    "camera": "a small round CCTV security camera on a high wall",
    "gate": "a tall reinforced steel gate, partially open",
    "fence": "a chain-link security fence topped with barbed wire",
    "guard": "a security guard tower silhouette at night",
    "passcode": "a keypad with glowing numbers on a secure door",
    "surveillance": "a dark room full of surveillance screens",
    "monitor": "a desk covered in glowing computer monitors",
    "server": "a long aisle of tall humming server racks with blinking LED lights",
    "server room": "a cold blue server room with rows of rack-mounted servers",
    "data center": "a vast data center hall with endless server racks and cold lighting",
    "hard drive": "a stack of hard drives and circuit boards on a workbench",
    "usb": "a single small USB drive on a dark desk",
    "laptop": "a sleek open laptop glowing on a dark desk",
    "computer": "a vintage computer with a glowing CRT monitor",
    "keyboard": "a worn keyboard with coffee stains, close up",
    "terminal": "a glowing green-on-black computer terminal",
    "cable": "a tangle of cables and wires behind a computer",
    "router": "a networking router with blinking ethernet lights",
    "server rack": "a tall server rack packed with drives and cables",

    # ---- Library / academic / study ----
    "academic halls": "a grand old university library with towering wooden bookshelves and vaulted ceilings",
    "library": "a vast two-storey library with towering dark-wood bookshelves and warm lamplight",
    "book": "a stack of old leather-bound books",
    "bookshelf": "a wall of tall dark-wood bookshelves crammed with books",
    "archive": "a dim archive room of floor-to-ceiling filing cabinets",
    "manuscript": "a delicate handwritten manuscript under a desk lamp",
    "ledger": "an old leather accounting ledger with handwritten numbers",
    "paper": "papers scattered across a cluttered desk",
    "document": "a folder of official documents",
    "file": "a row of metal filing cabinets",
    "cabinet": "a tall wooden filing cabinet with labeled drawers",
    "certificate": "a framed certificate on a wall",
    "diploma": "a framed diploma hanging in a study",
    "textbook": "a thick open textbook with diagrams",
    "parchment": "an aged parchment scroll",
    "map": "an old paper map spread across a table",
    "blueprint": "a large technical blueprint with building plans",
    "formula": "a chalkboard covered in dense mathematical formulas",
    "equation": "a whiteboard with a long complex equation",
    "notebook": "a spiral notebook full of dense handwritten notes",
    "pen": "a fountain pen resting on paper",
    "calculator": "a scientific calculator on a desk",
    "abacus": "an old wooden abacus",
    "blackboard": "a blackboard with chalk math equations",
    "whiteboard": "a whiteboard covered in marker diagrams",

    # ---- Gambling / lottery / cards ----
    "lottery ticket": "a bundle of colorful lottery scratch tickets",
    "lottery": "a lottery draw machine with numbered balls tumbling",
    "ticket": "a printed lottery ticket with numbers",
    "casino": "a dim casino floor with glowing slot machines and card tables",
    "cards": "a hand of playing cards spread on green felt",
    "playing cards": "a spread of playing cards on a casino table",
    "poker chip": "stacked poker chips on green felt",
    "chips": "towers of colored casino poker chips",
    "card table": "a green felt card table under a low lamp",
    "slot machine": "a row of bright slot machines",
    "roulette": "a roulette wheel spinning on a casino table",
    "dice": "a pair of dice mid-roll on felt",
    "betting slip": "a paper betting slip with handwritten odds",
    "jackpot": "a slot machine flashing with a massive jackpot amount",
    "blackjack": "a blackjack table with cards and chips",
    "poker": "a tense poker table under a green banker lamp",
    "probability": "a chart of probability distributions on paper",
    "numbers": "columns of numbers on a ledger page",
    "combination": "a sheet listing number combinations",
    "statistics": "a desk of statistical charts and graphs",
    "pattern": "a pattern of dots and sequences being analyzed",
    "sequence": "a long sequence of numbers being traced by hand",

    # ---- Money / finance ----
    "cash": "stacks of banded cash bills on a table",
    "money": "bundles of hundred-dollar bills",
    "banknote": "a single crisp banknote under a light",
    "bill": "a stack of paper bills",
    "coin": "a gleaming gold coin in close-up",
    "gold": "gold bars stacked in a strongbox",
    "gold bar": "stacked gold bullion bars glinting",
    "money bag": "a burlap money bag with a dollar sign",
    "cash register": "a vintage brass cash register with an open drawer",
    "bank": "the grand stone facade of a bank building at night",
    "check": "a signed personal check on a desk",
    "account": "a bank statement with a highlighted balance",
    "balance": "a ledger showing a large account balance",
    "deposit": "a bank deposit slip and cash on a counter",
    "withdrawal": "a withdrawal slip beside cash",
    "wire": "a glowing computer screen showing a bank transfer",
    "transfer": "a screen showing a wire transfer confirmation",
    "transaction": "a receipt and card on a counter",
    "receipt": "a long paper receipt trailing off a table",
    "invoice": "an invoice document stamped PAID",
    "ledger page": "a page of a financial ledger with neat columns",
    "vault door": "the massive circular door of a bank vault",

    # ---- Tools / technology / equipment ----
    "computer server": "a rack of servers with blinking lights",
    "gpu": "a large graphics card with twin fans",
    "processor": "a CPU chip on a motherboard, macro close-up",
    "chip": "a silicon microchip with glowing traces",
    "circuit board": "a green circuit board with copper traces",
    "motherboard": "a motherboard with components and heat sinks",
    "antenna": "a radio antenna on a rooftop",
    "satellite dish": "a large satellite dish against a night sky",
    "telescope": "a telescope aimed at a starry sky",
    "radio": "a vintage radio with glowing vacuum tubes",
    "hacker": "a figure at a dark desk lit only by screens",
    "screens": "multiple glowing monitors in a dark room",
    "console": "a glowing computer console with dials",
    "panel": "a wall of buttons and switches",
    "device": "a futuristic handheld device on a table",
    "machine": "a large industrial machine with gears",
    "engine": "a complex mechanical engine in cross-section",
    "generator": "a diesel generator in a basement",
    "circuit": "a close-up of a glowing circuit board",
    "software": "a screen showing lines of code",
    "code": "glowing code scrolling on a dark screen",
    "database": "a glowing holographic database interface",
    "encryption": "a padlock icon of encryption on a screen",

    # ---- Vehicle / transport ----
    "car": "a vintage car under a streetlight",
    "truck": "a large truck driving through rain at night",
    "van": "a parked white van in an alley",
    "train": "a train speeding through a tunnel",
    "subway": "an empty subway station platform",
    "station": "a grand old train station concourse",
    "airport": "a deserted airport terminal at night",
    "plane": "a plane on a rain-soaked tarmac",
    "boat": "a small boat on dark water",
    "ship": "a cargo ship at night",
    "helicopter": "a helicopter with a searchlight",
    "motorcycle": "a motorcycle parked on a street",
    "bike": "a bicycle chained to a railing",
    "garage": "a dim garage with tools and a workbench",
    "warehouse": "a vast warehouse full of crates",
    "loading dock": "a warehouse loading dock at night",
    "container": "stacked shipping containers",
    "crate": "a stack of wooden shipping crates",
    "suitcase": "a worn leather suitcase on a platform",
    "briefcase": "a black leather briefcase on a desk",
    "duffel bag": "a heavy duffel bag on a floor",

    # ---- Food / drug / smuggling (niche artifacts) ----
    "cigarette": "a cigarette glowing in the dark",
    "cigar": "a lit cigar trailing smoke",
    "medicine": "a bottle of prescription pills",
    "pills": "loose pills scattered on a table",
    "vial": "a small glass vial of clear liquid",
    "chemicals": "flasks and beakers of colored chemicals",
    "lab": "a chemistry lab with glassware and bunsen burners",
    "test tube": "a rack of test tubes with colored liquid",
    "beaker": "a glass beaker bubbling with liquid",
    "microscope": "a laboratory microscope",
    "gloves": "a pair of blue nitrile gloves",
    "syringe": "a syringe in close-up",
    "bottle": "a glass bottle on a table",
    "jar": "a glass jar on a shelf",

    # ---- Document / identity / fraud ----
    "passport": "an open passport with stamps",
    "id": "a forged ID card on a desk",
    "identity": "a stack of identity documents",
    "birth certificate": "an official birth certificate document",
    "signature": "a hand signing a document with a pen",
    "stamp": "a rubber stamp and ink pad",
    "seal": "a wax seal on a document",
    "sticker": "a sheet of stickers and labels",
    "printer": "an office printer outputting pages",
    "photocopy": "a stack of photocopied pages",
    "envelope": "a sealed envelope on a desk",
    "mail": "a pile of opened mail",
    "box": "a cardboard box on a table",
    "package": "a wrapped package with tape",
    "label": "a barcode label being scanned",

    # ---- Locations / interiors ----
    "academic": "a grand old university campus with stone buildings",
    "campus": "a wide shot of a university campus quad",
    "office": "a modern open-plan office at night",
    "penthouse": "a high-rise penthouse with floor-to-ceiling windows",
    "apartment": "a cramped old apartment lit by a single lamp",
    "basement": "a dim concrete basement",
    "attic": "a dusty attic full of boxes",
    "corridor": "a long empty institutional corridor",
    "hall": "a grand echoing hallway",
    "halls": "a grand echoing hallway of an old institution",
    "classroom": "an empty university classroom",
    "auditorium": "a vast empty auditorium",
    "lobby": "a marble building lobby",
    "boardroom": "a long boardroom table under warm light",
    "conference room": "a glass conference room at night",
    "warehouse interior": "a cavernous warehouse interior with high shelves",
    "factory": "a factory floor with machinery and steam",
    "plant": "an industrial plant with pipes and tanks",
    "roof": "a city rooftop at night",
    "rooftop": "a rooftop overlooking a city skyline",
    "alley": "a narrow rain-slicked alley",
    "street": "a deserted street at night under a streetlight",
    "bridge": "a large bridge over dark water at night",
    "parking garage": "a multi-level concrete parking garage",
    "hotel": "a hotel corridor with doors",
    "motel": "a neon motel sign at night",
    "phone booth": "a classic red phone booth on a street",
    "payphone": "an old payphone on a wall",
    "elevator": "a mirrored elevator interior",
    "stairwell": "a concrete stairwell spiraling down",
    "rooftop access": "a fire door opening onto a rooftop",
}
